spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  redis:
    host: 103.152.165.18
    port: 6379
    password: 123456a@
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: nftmarket-account-svc
          uri: 'lb://account-svc'
          predicates:
            - Path=/account-svc/**
          filters:
            - 'RewritePath=/account-svc/(?<path>.*), /$\{path}'
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        - id: nftmarket-core-svc
          uri: 'lb://core-svc'
          predicates:
            - Path=/core-svc/**
          filters:
            - 'RewritePath=/core-svc/(?<path>.*), /$\{path}'
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        - id: nftmarket-api-svc
          uri: 'lb://api-svc'
          predicates:
            - Path=/api-svc/**
          filters:
            - 'RewritePath=/api-svc/(?<path>.*), /$\{path}'
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
server:
  port: '${GATEWAY_PORT:31000}'
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
eureka:
  client:
    serviceUrl:
      defaultZone: '${EUREKA_URI:http://localhost:30000/eureka/}'
hystrix:
  command:
    enrollmentsvc:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
enrollmentsvc:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 20000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
logging:
  config: config/log4j2.xml